version: '2.0'

services:
  otp:
    image: aelissa/otp
    restart: unless-stopped
    ports:
      - 8080:8080
    volumes:
      - ./graphs:/var/otp/graphs
    environment:
      - JAVA_OPTIONS=-Xmx8G
    command:
      [
        '--server',
        '--maxThreads 7',
        '--analyst',
        '--autoScan',
        '--insecure',
        '--verbose',
      ]

  otpr:
    image: aelissa/otpr
    ports:
      - "8888:8787"
    environment:
      - PASSWORD=
      - USER=
    volumes:
      - /home/your-user/docker-otp/example:/home/your-user/rstudio/


